title:        Dx.Yang
tagline:      'Dx.Yang'
description:  'Programmer'
url:          http://xbingoz.com
version:      1.1.1
author:
  name:       'Dx.Yang'
  email:      'x6doooo@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
